<script setup>
defineProps({
  images: { type: Array, required: true },
});
</script>

<template>
  <div class="specimen-field" role="group" aria-label="Examples of cards generated by MehrakBot">
    <figure v-for="(image, index) in images.slice(0, 3)" :key="image.src" class="specimen">
      <span class="index" aria-hidden="true">0{{ index + 1 }}</span>
      <img :src="image.src" :alt="image.alt" />
    </figure>
  </div>
</template>

<style scoped>
.specimen-field {
  position: relative;
  min-height: clamp(21rem, 43vw, 38rem);
  isolation: isolate;
}

.specimen-field::before {
  content: "";
  position: absolute;
  inset: 7% 3% 10% 13%;
  z-index: -1;
  border: 1px solid var(--border-primary);
  background:
    linear-gradient(var(--border-primary) 1px, transparent 1px),
    linear-gradient(90deg, var(--border-primary) 1px, transparent 1px);
  background-size: 2.5rem 2.5rem;
  opacity: 0.42;
  transform: rotate(2deg);
}

.specimen {
  position: absolute;
  margin: 0;
  padding: var(--space-2);
  border: 1px solid var(--border-secondary);
  background: var(--bg-surface);
  box-shadow: var(--shadow-lg);
  animation: settle var(--motion-slow) var(--ease-enter) both;
}

.specimen:nth-child(1) {
  top: 7%;
  right: 0;
  width: 86%;
  z-index: 3;
  transform: rotate(1.5deg);
}

.specimen:nth-child(2) {
  bottom: 0;
  left: 0;
  width: 48%;
  z-index: 4;
  transform: rotate(-3deg);
  animation-delay: 100ms;
}

.specimen:nth-child(3) {
  right: 5%;
  bottom: 3%;
  width: 43%;
  z-index: 2;
  transform: rotate(4deg);
  animation-delay: 180ms;
}

.specimen img {
  display: block;
  width: 100%;
  max-height: 22rem;
  object-fit: contain;
}

.index {
  position: absolute;
  top: calc(-1 * var(--space-6));
  left: 0;
  color: var(--brass);
  font-family: var(--font-mono);
  font-size: var(--text-xs);
  letter-spacing: 0.12em;
}

@keyframes settle {
  from {
    opacity: 0;
    translate: 0 2rem;
  }
}

@media (max-width: 40rem) {
  .specimen-field {
    min-height: 20rem;
  }
}
</style>
